from enum import Enum


class AnalyticsTableHookResourceTableType(str, Enum):
    CATEGORY_OPTION_COMBO_NAME = "CATEGORY_OPTION_COMBO_NAME"
    CATEGORY_STRUCTURE = "CATEGORY_STRUCTURE"
    DATA_APPROVAL_MIN_LEVEL = "DATA_APPROVAL_MIN_LEVEL"
    DATA_APPROVAL_REMAP_LEVEL = "DATA_APPROVAL_REMAP_LEVEL"
    DATA_ELEMENT_CATEGORY_OPTION_COMBO = "DATA_ELEMENT_CATEGORY_OPTION_COMBO"
    DATA_ELEMENT_GROUP_SET_STRUCTURE = "DATA_ELEMENT_GROUP_SET_STRUCTURE"
    DATA_ELEMENT_STRUCTURE = "DATA_ELEMENT_STRUCTURE"
    DATA_SET_ORG_UNIT_CATEGORY = "DATA_SET_ORG_UNIT_CATEGORY"
    DATE_PERIOD_STRUCTURE = "DATE_PERIOD_STRUCTURE"
    INDICATOR_GROUP_SET_STRUCTURE = "INDICATOR_GROUP_SET_STRUCTURE"
    ORG_UNIT_GROUP_SET_STRUCTURE = "ORG_UNIT_GROUP_SET_STRUCTURE"
    ORG_UNIT_STRUCTURE = "ORG_UNIT_STRUCTURE"
    PERIOD_STRUCTURE = "PERIOD_STRUCTURE"

    def __str__(self) -> str:
        return str(self.value)
