from enum import Enum


class AppAppState(str, Enum):
    APPROVED = "APPROVED"
    DELETION_IN_PROGRESS = "DELETION_IN_PROGRESS"
    INSTALLATION_FAILED = "INSTALLATION_FAILED"
    INVALID_BUNDLED_APP_OVERRIDE = "INVALID_BUNDLED_APP_OVERRIDE"
    INVALID_CORE_APP = "INVALID_CORE_APP"
    INVALID_MANIFEST_JSON = "INVALID_MANIFEST_JSON"
    INVALID_ZIP_FORMAT = "INVALID_ZIP_FORMAT"
    MISSING_MANIFEST = "MISSING_MANIFEST"
    MISSING_SYSTEM_BASE_URL = "MISSING_SYSTEM_BASE_URL"
    NAMESPACE_TAKEN = "NAMESPACE_TAKEN"
    NOT_APPROVED = "NOT_APPROVED"
    NOT_FOUND = "NOT_FOUND"
    OK = "OK"
    PENDING = "PENDING"

    def __str__(self) -> str:
        return str(self.value)
