from enum import Enum


class ContinuousAnalyticsJobParametersSkipTableTypesItem(str, Enum):
    COMPLETENESS = "COMPLETENESS"
    COMPLETENESS_TARGET = "COMPLETENESS_TARGET"
    DATA_VALUE = "DATA_VALUE"
    ENROLLMENT = "ENROLLMENT"
    EVENT = "EVENT"
    ORG_UNIT_TARGET = "ORG_UNIT_TARGET"
    OWNERSHIP = "OWNERSHIP"
    TRACKED_ENTITY_INSTANCE = "TRACKED_ENTITY_INSTANCE"
    TRACKED_ENTITY_INSTANCE_ENROLLMENTS = "TRACKED_ENTITY_INSTANCE_ENROLLMENTS"
    TRACKED_ENTITY_INSTANCE_EVENTS = "TRACKED_ENTITY_INSTANCE_EVENTS"
    VALIDATION_RESULT = "VALIDATION_RESULT"

    def __str__(self) -> str:
        return str(self.value)
