from enum import Enum


class DataStatisticsGetTopFavoritesEventType(str, Enum):
    ACTIVE_USERS = "ACTIVE_USERS"
    DASHBOARD_VIEW = "DASHBOARD_VIEW"
    DATA_SET_REPORT_VIEW = "DATA_SET_REPORT_VIEW"
    EVENT_CHART_VIEW = "EVENT_CHART_VIEW"
    EVENT_REPORT_VIEW = "EVENT_REPORT_VIEW"
    EVENT_VISUALIZATION_VIEW = "EVENT_VISUALIZATION_VIEW"
    MAP_VIEW = "MAP_VIEW"
    PASSIVE_DASHBOARD_VIEW = "PASSIVE_DASHBOARD_VIEW"
    TOTAL_VIEW = "TOTAL_VIEW"
    VISUALIZATION_VIEW = "VISUALIZATION_VIEW"

    def __str__(self) -> str:
        return str(self.value)
