from enum import Enum


class DataDimensionItemDataDimensionItemType(str, Enum):
    DATA_ELEMENT = "DATA_ELEMENT"
    DATA_ELEMENT_OPERAND = "DATA_ELEMENT_OPERAND"
    EXPRESSION_DIMENSION_ITEM = "EXPRESSION_DIMENSION_ITEM"
    INDICATOR = "INDICATOR"
    PROGRAM_ATTRIBUTE = "PROGRAM_ATTRIBUTE"
    PROGRAM_DATA_ELEMENT = "PROGRAM_DATA_ELEMENT"
    PROGRAM_INDICATOR = "PROGRAM_INDICATOR"
    REPORTING_RATE = "REPORTING_RATE"
    SUBEXPRESSION_DIMENSION_ITEM = "SUBEXPRESSION_DIMENSION_ITEM"
    VALIDATION_RULE = "VALIDATION_RULE"

    def __str__(self) -> str:
        return str(self.value)
