from enum import Enum


class IndicatorGetObjectPropertyGistAsCsvProperty(str, Enum):
    ACCESS = "access"
    AGGREGATEEXPORTATTRIBUTEOPTIONCOMBO = "aggregateExportAttributeOptionCombo"
    AGGREGATEEXPORTCATEGORYOPTIONCOMBO = "aggregateExportCategoryOptionCombo"
    AGGREGATIONTYPE = "aggregationType"
    ANNUALIZED = "annualized"
    ATTRIBUTEVALUES = "attributeValues"
    CODE = "code"
    CREATED = "created"
    CREATEDBY = "createdBy"
    DATASETS = "dataSets"
    DECIMALS = "decimals"
    DENOMINATOR = "denominator"
    DENOMINATORDESCRIPTION = "denominatorDescription"
    DESCRIPTION = "description"
    DIMENSIONITEM = "dimensionItem"
    DISPLAYDENOMINATORDESCRIPTION = "displayDenominatorDescription"
    DISPLAYDESCRIPTION = "displayDescription"
    DISPLAYFORMNAME = "displayFormName"
    DISPLAYNAME = "displayName"
    DISPLAYNUMERATORDESCRIPTION = "displayNumeratorDescription"
    DISPLAYSHORTNAME = "displayShortName"
    EXPLODEDDENOMINATOR = "explodedDenominator"
    EXPLODEDNUMERATOR = "explodedNumerator"
    FAVORITE = "favorite"
    FAVORITES = "favorites"
    FORMNAME = "formName"
    HREF = "href"
    ID = "id"
    INDICATORGROUPS = "indicatorGroups"
    INDICATORTYPE = "indicatorType"
    LASTUPDATED = "lastUpdated"
    LASTUPDATEDBY = "lastUpdatedBy"
    LEGENDSET = "legendSet"
    LEGENDSETS = "legendSets"
    NAME = "name"
    NUMERATOR = "numerator"
    NUMERATORDESCRIPTION = "numeratorDescription"
    QUERYMODS = "queryMods"
    SHARING = "sharing"
    SHORTNAME = "shortName"
    STYLE = "style"
    TRANSLATIONS = "translations"
    URL = "url"
    USER = "user"

    def __str__(self) -> str:
        return str(self.value)
