from enum import Enum


class JobConfigurationAddCollectionItemProperty(str, Enum):
    ACCESS = "access"
    ATTRIBUTEVALUES = "attributeValues"
    CODE = "code"
    CONFIGURABLE = "configurable"
    CREATED = "created"
    CREATEDBY = "createdBy"
    CRONEXPRESSION = "cronExpression"
    DELAY = "delay"
    DISPLAYNAME = "displayName"
    ENABLED = "enabled"
    ERRORCODES = "errorCodes"
    EXECUTEDBY = "executedBy"
    FAVORITE = "favorite"
    FAVORITES = "favorites"
    HREF = "href"
    ID = "id"
    JOBPARAMETERS = "jobParameters"
    JOBSTATUS = "jobStatus"
    JOBTYPE = "jobType"
    LASTALIVE = "lastAlive"
    LASTEXECUTED = "lastExecuted"
    LASTEXECUTEDSTATUS = "lastExecutedStatus"
    LASTFINISHED = "lastFinished"
    LASTRUNTIMEEXECUTION = "lastRuntimeExecution"
    LASTUPDATED = "lastUpdated"
    LASTUPDATEDBY = "lastUpdatedBy"
    LEADERONLYJOB = "leaderOnlyJob"
    MAXDELAYEDEXECUTIONTIME = "maxDelayedExecutionTime"
    NAME = "name"
    NEXTEXECUTIONTIME = "nextExecutionTime"
    QUEUENAME = "queueName"
    QUEUEPOSITION = "queuePosition"
    SCHEDULINGTYPE = "schedulingType"
    SHARING = "sharing"
    TRANSLATIONS = "translations"
    USER = "user"
    USERUID = "userUid"

    def __str__(self) -> str:
        return str(self.value)
