from enum import Enum


class MetadataImportExportGetCsvImportClassesResponse200Item(str, Enum):
    CATEGORY = "CATEGORY"
    CATEGORY_COMBO = "CATEGORY_COMBO"
    CATEGORY_OPTION = "CATEGORY_OPTION"
    CATEGORY_OPTION_GROUP = "CATEGORY_OPTION_GROUP"
    DATA_ELEMENT = "DATA_ELEMENT"
    DATA_ELEMENT_GROUP = "DATA_ELEMENT_GROUP"
    DATA_ELEMENT_GROUP_MEMBERSHIP = "DATA_ELEMENT_GROUP_MEMBERSHIP"
    INDICATOR = "INDICATOR"
    INDICATOR_GROUP_MEMBERSHIP = "INDICATOR_GROUP_MEMBERSHIP"
    OPTION_GROUP = "OPTION_GROUP"
    OPTION_GROUP_SET = "OPTION_GROUP_SET"
    OPTION_GROUP_SET_MEMBERSHIP = "OPTION_GROUP_SET_MEMBERSHIP"
    OPTION_SET = "OPTION_SET"
    ORGANISATION_UNIT = "ORGANISATION_UNIT"
    ORGANISATION_UNIT_GROUP = "ORGANISATION_UNIT_GROUP"
    ORGANISATION_UNIT_GROUP_MEMBERSHIP = "ORGANISATION_UNIT_GROUP_MEMBERSHIP"
    VALIDATION_RULE = "VALIDATION_RULE"

    def __str__(self) -> str:
        return str(self.value)
