from enum import Enum


class MetadataItemDimensionItemType(str, Enum):
    CATEGORY_OPTION = "CATEGORY_OPTION"
    CATEGORY_OPTION_GROUP = "CATEGORY_OPTION_GROUP"
    DATA_ELEMENT = "DATA_ELEMENT"
    DATA_ELEMENT_GROUP = "DATA_ELEMENT_GROUP"
    DATA_ELEMENT_OPERAND = "DATA_ELEMENT_OPERAND"
    EXPRESSION_DIMENSION_ITEM = "EXPRESSION_DIMENSION_ITEM"
    INDICATOR = "INDICATOR"
    OPTION_GROUP = "OPTION_GROUP"
    ORGANISATION_UNIT = "ORGANISATION_UNIT"
    ORGANISATION_UNIT_GROUP = "ORGANISATION_UNIT_GROUP"
    PERIOD = "PERIOD"
    PROGRAM_ATTRIBUTE = "PROGRAM_ATTRIBUTE"
    PROGRAM_DATA_ELEMENT = "PROGRAM_DATA_ELEMENT"
    PROGRAM_INDICATOR = "PROGRAM_INDICATOR"
    REPORTING_RATE = "REPORTING_RATE"
    SUBEXPRESSION_DIMENSION_ITEM = "SUBEXPRESSION_DIMENSION_ITEM"

    def __str__(self) -> str:
        return str(self.value)
