from enum import Enum


class ObjectValueTypeRenderingOptionRenderingTypesItem(str, Enum):
    AUTOCOMPLETE = "AUTOCOMPLETE"
    BAR_CODE = "BAR_CODE"
    CANVAS = "CANVAS"
    DEFAULT = "DEFAULT"
    DROPDOWN = "DROPDOWN"
    GS1_DATAMATRIX = "GS1_DATAMATRIX"
    HORIZONTAL_CHECKBOXES = "HORIZONTAL_CHECKBOXES"
    HORIZONTAL_RADIOBUTTONS = "HORIZONTAL_RADIOBUTTONS"
    ICON = "ICON"
    ICONS_AS_BUTTONS = "ICONS_AS_BUTTONS"
    LINEAR_SCALE = "LINEAR_SCALE"
    QR_CODE = "QR_CODE"
    SHARED_HEADER_RADIOBUTTONS = "SHARED_HEADER_RADIOBUTTONS"
    SLIDER = "SLIDER"
    SPINNER = "SPINNER"
    TOGGLE = "TOGGLE"
    VALUE = "VALUE"
    VERTICAL_CHECKBOXES = "VERTICAL_CHECKBOXES"
    VERTICAL_RADIOBUTTONS = "VERTICAL_RADIOBUTTONS"

    def __str__(self) -> str:
        return str(self.value)
