from enum import Enum


class OptionGroupSetDeleteCollectionItemProperty(str, Enum):
    ACCESS = "access"
    AGGREGATIONTYPE = "aggregationType"
    ALLITEMS = "allItems"
    ATTRIBUTEVALUES = "attributeValues"
    CODE = "code"
    CREATED = "created"
    CREATEDBY = "createdBy"
    DATADIMENSION = "dataDimension"
    DATADIMENSIONTYPE = "dataDimensionType"
    DESCRIPTION = "description"
    DIMENSION = "dimension"
    DIMENSIONITEMKEYWORDS = "dimensionItemKeywords"
    DISPLAYDESCRIPTION = "displayDescription"
    DISPLAYFORMNAME = "displayFormName"
    DISPLAYNAME = "displayName"
    DISPLAYSHORTNAME = "displayShortName"
    FAVORITE = "favorite"
    FAVORITES = "favorites"
    FILTER = "filter"
    FORMNAME = "formName"
    HREF = "href"
    ID = "id"
    ITEMS = "items"
    LASTUPDATED = "lastUpdated"
    LASTUPDATEDBY = "lastUpdatedBy"
    LEGENDSET = "legendSet"
    NAME = "name"
    OPTIONGROUPS = "optionGroups"
    OPTIONSET = "optionSet"
    PROGRAM = "program"
    PROGRAMSTAGE = "programStage"
    REPETITION = "repetition"
    SHARING = "sharing"
    SHORTNAME = "shortName"
    TRANSLATIONS = "translations"
    USER = "user"
    VALUETYPE = "valueType"

    def __str__(self) -> str:
        return str(self.value)
