from enum import Enum


class OrganisationUnitAddCollectionItemProperty(str, Enum):
    ACCESS = "access"
    ADDRESS = "address"
    AGGREGATIONTYPE = "aggregationType"
    ANCESTORS = "ancestors"
    ATTRIBUTEVALUES = "attributeValues"
    CHILDREN = "children"
    CLOSEDDATE = "closedDate"
    CODE = "code"
    COMMENT = "comment"
    CONTACTPERSON = "contactPerson"
    CREATED = "created"
    CREATEDBY = "createdBy"
    DATASETS = "dataSets"
    DESCRIPTION = "description"
    DIMENSIONITEM = "dimensionItem"
    DISPLAYDESCRIPTION = "displayDescription"
    DISPLAYFORMNAME = "displayFormName"
    DISPLAYNAME = "displayName"
    DISPLAYSHORTNAME = "displayShortName"
    EMAIL = "email"
    FAVORITE = "favorite"
    FAVORITES = "favorites"
    FORMNAME = "formName"
    GEOMETRY = "geometry"
    HREF = "href"
    ID = "id"
    IMAGE = "image"
    LASTUPDATED = "lastUpdated"
    LASTUPDATEDBY = "lastUpdatedBy"
    LEAF = "leaf"
    LEGENDSET = "legendSet"
    LEGENDSETS = "legendSets"
    LEVEL = "level"
    MEMBERCOUNT = "memberCount"
    NAME = "name"
    OPENINGDATE = "openingDate"
    ORGANISATIONUNITGROUPS = "organisationUnitGroups"
    PARENT = "parent"
    PATH = "path"
    PHONENUMBER = "phoneNumber"
    PROGRAMS = "programs"
    QUERYMODS = "queryMods"
    SHARING = "sharing"
    SHORTNAME = "shortName"
    TRANSLATIONS = "translations"
    TYPE = "type"
    URL = "url"
    USER = "user"
    USERS = "users"

    def __str__(self) -> str:
        return str(self.value)
