from enum import Enum


class ProgramIndicatorGetObjectPropertyGistAsCsvProperty(str, Enum):
    ACCESS = "access"
    AGGREGATEEXPORTATTRIBUTEOPTIONCOMBO = "aggregateExportAttributeOptionCombo"
    AGGREGATEEXPORTCATEGORYOPTIONCOMBO = "aggregateExportCategoryOptionCombo"
    AGGREGATIONTYPE = "aggregationType"
    ANALYTICSPERIODBOUNDARIES = "analyticsPeriodBoundaries"
    ANALYTICSTYPE = "analyticsType"
    ATTRIBUTEVALUES = "attributeValues"
    CODE = "code"
    CREATED = "created"
    CREATEDBY = "createdBy"
    DECIMALS = "decimals"
    DESCRIPTION = "description"
    DIMENSIONITEM = "dimensionItem"
    DISPLAYDESCRIPTION = "displayDescription"
    DISPLAYFORMNAME = "displayFormName"
    DISPLAYINFORM = "displayInForm"
    DISPLAYNAME = "displayName"
    DISPLAYSHORTNAME = "displayShortName"
    EXPRESSION = "expression"
    FAVORITE = "favorite"
    FAVORITES = "favorites"
    FILTER = "filter"
    FORMNAME = "formName"
    HREF = "href"
    ID = "id"
    LASTUPDATED = "lastUpdated"
    LASTUPDATEDBY = "lastUpdatedBy"
    LEGENDSET = "legendSet"
    LEGENDSETS = "legendSets"
    NAME = "name"
    ORGUNITFIELD = "orgUnitField"
    PROGRAM = "program"
    PROGRAMINDICATORGROUPS = "programIndicatorGroups"
    QUERYMODS = "queryMods"
    SHARING = "sharing"
    SHORTNAME = "shortName"
    STYLE = "style"
    TRANSLATIONS = "translations"
    USER = "user"

    def __str__(self) -> str:
        return str(self.value)
