from enum import Enum


class ProgramStageGetObjectPropertyGistAsCsvProperty(str, Enum):
    ACCESS = "access"
    ALLOWGENERATENEXTVISIT = "allowGenerateNextVisit"
    ATTRIBUTEVALUES = "attributeValues"
    AUTOGENERATEEVENT = "autoGenerateEvent"
    BLOCKENTRYFORM = "blockEntryForm"
    CODE = "code"
    CREATED = "created"
    CREATEDBY = "createdBy"
    DATAENTRYFORM = "dataEntryForm"
    DESCRIPTION = "description"
    DISPLAYDESCRIPTION = "displayDescription"
    DISPLAYDUEDATELABEL = "displayDueDateLabel"
    DISPLAYEVENTLABEL = "displayEventLabel"
    DISPLAYEXECUTIONDATELABEL = "displayExecutionDateLabel"
    DISPLAYFORMNAME = "displayFormName"
    DISPLAYGENERATEEVENTBOX = "displayGenerateEventBox"
    DISPLAYNAME = "displayName"
    DISPLAYPROGRAMSTAGELABEL = "displayProgramStageLabel"
    DISPLAYSHORTNAME = "displayShortName"
    DUEDATELABEL = "dueDateLabel"
    ENABLEUSERASSIGNMENT = "enableUserAssignment"
    EVENTLABEL = "eventLabel"
    EXECUTIONDATELABEL = "executionDateLabel"
    FAVORITE = "favorite"
    FAVORITES = "favorites"
    FEATURETYPE = "featureType"
    FORMNAME = "formName"
    FORMTYPE = "formType"
    GENERATEDBYENROLLMENTDATE = "generatedByEnrollmentDate"
    HIDEDUEDATE = "hideDueDate"
    HREF = "href"
    ID = "id"
    LASTUPDATED = "lastUpdated"
    LASTUPDATEDBY = "lastUpdatedBy"
    MINDAYSFROMSTART = "minDaysFromStart"
    NAME = "name"
    NEXTSCHEDULEDATE = "nextScheduleDate"
    NOTIFICATIONTEMPLATES = "notificationTemplates"
    OPENAFTERENROLLMENT = "openAfterEnrollment"
    PERIODTYPE = "periodType"
    PREGENERATEUID = "preGenerateUID"
    PROGRAM = "program"
    PROGRAMSTAGEDATAELEMENTS = "programStageDataElements"
    PROGRAMSTAGELABEL = "programStageLabel"
    PROGRAMSTAGESECTIONS = "programStageSections"
    REFERRAL = "referral"
    REMINDCOMPLETED = "remindCompleted"
    REPEATABLE = "repeatable"
    REPORTDATETOUSE = "reportDateToUse"
    SHARING = "sharing"
    SHORTNAME = "shortName"
    SORTORDER = "sortOrder"
    STANDARDINTERVAL = "standardInterval"
    STYLE = "style"
    TRANSLATIONS = "translations"
    USER = "user"
    VALIDATIONSTRATEGY = "validationStrategy"

    def __str__(self) -> str:
        return str(self.value)
