from enum import Enum


class ProgramRuleVariableProgramRuleVariableSourceType(str, Enum):
    CALCULATED_VALUE = "CALCULATED_VALUE"
    DATAELEMENT_CURRENT_EVENT = "DATAELEMENT_CURRENT_EVENT"
    DATAELEMENT_NEWEST_EVENT_PROGRAM = "DATAELEMENT_NEWEST_EVENT_PROGRAM"
    DATAELEMENT_NEWEST_EVENT_PROGRAM_STAGE = "DATAELEMENT_NEWEST_EVENT_PROGRAM_STAGE"
    DATAELEMENT_PREVIOUS_EVENT = "DATAELEMENT_PREVIOUS_EVENT"
    TEI_ATTRIBUTE = "TEI_ATTRIBUTE"

    def __str__(self) -> str:
        return str(self.value)
