from enum import Enum


class PropertyNamesDataElement(str, Enum):
    ACCESS = "access"
    AGGREGATIONLEVELS = "aggregationLevels"
    AGGREGATIONTYPE = "aggregationType"
    ATTRIBUTEVALUES = "attributeValues"
    CATEGORYCOMBO = "categoryCombo"
    CODE = "code"
    COMMENTOPTIONSET = "commentOptionSet"
    CREATED = "created"
    CREATEDBY = "createdBy"
    DATAELEMENTGROUPS = "dataElementGroups"
    DATASETELEMENTS = "dataSetElements"
    DESCRIPTION = "description"
    DIMENSIONITEM = "dimensionItem"
    DISPLAYDESCRIPTION = "displayDescription"
    DISPLAYFORMNAME = "displayFormName"
    DISPLAYNAME = "displayName"
    DISPLAYSHORTNAME = "displayShortName"
    DOMAINTYPE = "domainType"
    FAVORITE = "favorite"
    FAVORITES = "favorites"
    FIELDMASK = "fieldMask"
    FORMNAME = "formName"
    HREF = "href"
    ID = "id"
    LASTUPDATED = "lastUpdated"
    LASTUPDATEDBY = "lastUpdatedBy"
    LEGENDSET = "legendSet"
    LEGENDSETS = "legendSets"
    NAME = "name"
    OPTIONSET = "optionSet"
    OPTIONSETVALUE = "optionSetValue"
    QUERYMODS = "queryMods"
    SHARING = "sharing"
    SHORTNAME = "shortName"
    STYLE = "style"
    TRANSLATIONS = "translations"
    URL = "url"
    USER = "user"
    VALUETYPE = "valueType"
    VALUETYPEOPTIONS = "valueTypeOptions"
    ZEROISSIGNIFICANT = "zeroIsSignificant"

    def __str__(self) -> str:
        return str(self.value)
