from enum import Enum


class PropertyNamesValidationRule(str, Enum):
    ACCESS = "access"
    AGGREGATEEXPORTATTRIBUTEOPTIONCOMBO = "aggregateExportAttributeOptionCombo"
    AGGREGATEEXPORTCATEGORYOPTIONCOMBO = "aggregateExportCategoryOptionCombo"
    AGGREGATIONTYPE = "aggregationType"
    ATTRIBUTEVALUES = "attributeValues"
    CODE = "code"
    CREATED = "created"
    CREATEDBY = "createdBy"
    DESCRIPTION = "description"
    DIMENSIONITEM = "dimensionItem"
    DIMENSIONITEMTYPE = "dimensionItemType"
    DISPLAYDESCRIPTION = "displayDescription"
    DISPLAYFORMNAME = "displayFormName"
    DISPLAYINSTRUCTION = "displayInstruction"
    DISPLAYNAME = "displayName"
    DISPLAYSHORTNAME = "displayShortName"
    FAVORITE = "favorite"
    FAVORITES = "favorites"
    FORMNAME = "formName"
    HREF = "href"
    ID = "id"
    IMPORTANCE = "importance"
    INSTRUCTION = "instruction"
    LASTUPDATED = "lastUpdated"
    LASTUPDATEDBY = "lastUpdatedBy"
    LEFTSIDE = "leftSide"
    LEGENDSET = "legendSet"
    LEGENDSETS = "legendSets"
    NAME = "name"
    NOTIFICATIONTEMPLATES = "notificationTemplates"
    OPERATOR = "operator"
    ORGANISATIONUNITLEVELS = "organisationUnitLevels"
    PERIODTYPE = "periodType"
    QUERYMODS = "queryMods"
    RIGHTSIDE = "rightSide"
    SHARING = "sharing"
    SHORTNAME = "shortName"
    SKIPFORMVALIDATION = "skipFormValidation"
    TRANSLATIONS = "translations"
    USER = "user"
    VALIDATIONRULEGROUPS = "validationRuleGroups"

    def __str__(self) -> str:
        return str(self.value)
