from enum import Enum


class SMSCommandParserType(str, Enum):
    ALERT_PARSER = "ALERT_PARSER"
    EVENT_REGISTRATION_PARSER = "EVENT_REGISTRATION_PARSER"
    J2ME_PARSER = "J2ME_PARSER"
    KEY_VALUE_PARSER = "KEY_VALUE_PARSER"
    PROGRAM_STAGE_DATAENTRY_PARSER = "PROGRAM_STAGE_DATAENTRY_PARSER"
    TRACKED_ENTITY_REGISTRATION_PARSER = "TRACKED_ENTITY_REGISTRATION_PARSER"
    UNREGISTERED_PARSER = "UNREGISTERED_PARSER"

    def __str__(self) -> str:
        return str(self.value)
