from enum import Enum


class SourceParamsPeriodTypesItem(str, Enum):
    BI_MONTHLY = "BI_MONTHLY"
    BI_WEEKLY = "BI_WEEKLY"
    DAILY = "DAILY"
    FINANCIAL_APRIL = "FINANCIAL_APRIL"
    FINANCIAL_JULY = "FINANCIAL_JULY"
    FINANCIAL_NOV = "FINANCIAL_NOV"
    FINANCIAL_OCT = "FINANCIAL_OCT"
    MONTHLY = "MONTHLY"
    QUARTERLY = "QUARTERLY"
    QUARTERLY_NOV = "QUARTERLY_NOV"
    SIX_MONTHLY = "SIX_MONTHLY"
    SIX_MONTHLY_APRIL = "SIX_MONTHLY_APRIL"
    SIX_MONTHLY_NOV = "SIX_MONTHLY_NOV"
    TWO_YEARLY = "TWO_YEARLY"
    WEEKLY = "WEEKLY"
    WEEKLY_SATURDAY = "WEEKLY_SATURDAY"
    WEEKLY_SUNDAY = "WEEKLY_SUNDAY"
    WEEKLY_THURSDAY = "WEEKLY_THURSDAY"
    WEEKLY_WEDNESDAY = "WEEKLY_WEDNESDAY"
    YEARLY = "YEARLY"

    def __str__(self) -> str:
        return str(self.value)
