from enum import Enum


class TrackerAttributeValueType(str, Enum):
    AGE = "AGE"
    BOOLEAN = "BOOLEAN"
    COORDINATE = "COORDINATE"
    DATE = "DATE"
    DATETIME = "DATETIME"
    EMAIL = "EMAIL"
    FILE_RESOURCE = "FILE_RESOURCE"
    GEOJSON = "GEOJSON"
    IMAGE = "IMAGE"
    INTEGER = "INTEGER"
    INTEGER_NEGATIVE = "INTEGER_NEGATIVE"
    INTEGER_POSITIVE = "INTEGER_POSITIVE"
    INTEGER_ZERO_OR_POSITIVE = "INTEGER_ZERO_OR_POSITIVE"
    LETTER = "LETTER"
    LONG_TEXT = "LONG_TEXT"
    MULTI_TEXT = "MULTI_TEXT"
    NUMBER = "NUMBER"
    ORGANISATION_UNIT = "ORGANISATION_UNIT"
    PERCENTAGE = "PERCENTAGE"
    PHONE_NUMBER = "PHONE_NUMBER"
    REFERENCE = "REFERENCE"
    TEXT = "TEXT"
    TIME = "TIME"
    TRACKER_ASSOCIATE = "TRACKER_ASSOCIATE"
    TRUE_ONLY = "TRUE_ONLY"
    UNIT_INTERVAL = "UNIT_INTERVAL"
    URL = "URL"
    USERNAME = "USERNAME"

    def __str__(self) -> str:
        return str(self.value)
