from enum import Enum


class TrackedEntityAttributeReplaceCollectionItemsJsonreplaceCollectionItemsXmlProperty(str, Enum):
    ACCESS = "access"
    AGGREGATIONTYPE = "aggregationType"
    ATTRIBUTEVALUES = "attributeValues"
    CODE = "code"
    CONFIDENTIAL = "confidential"
    CREATED = "created"
    CREATEDBY = "createdBy"
    DESCRIPTION = "description"
    DIMENSIONITEM = "dimensionItem"
    DISPLAYDESCRIPTION = "displayDescription"
    DISPLAYFORMNAME = "displayFormName"
    DISPLAYINLISTNOPROGRAM = "displayInListNoProgram"
    DISPLAYNAME = "displayName"
    DISPLAYONVISITSCHEDULE = "displayOnVisitSchedule"
    DISPLAYSHORTNAME = "displayShortName"
    EXPRESSION = "expression"
    FAVORITE = "favorite"
    FAVORITES = "favorites"
    FIELDMASK = "fieldMask"
    FORMNAME = "formName"
    GENERATED = "generated"
    HREF = "href"
    ID = "id"
    INHERIT = "inherit"
    LASTUPDATED = "lastUpdated"
    LASTUPDATEDBY = "lastUpdatedBy"
    LEGENDSET = "legendSet"
    LEGENDSETS = "legendSets"
    NAME = "name"
    OPTIONSET = "optionSet"
    OPTIONSETVALUE = "optionSetValue"
    ORGUNITSCOPE = "orgunitScope"
    PATTERN = "pattern"
    QUERYMODS = "queryMods"
    SHARING = "sharing"
    SHORTNAME = "shortName"
    SKIPSYNCHRONIZATION = "skipSynchronization"
    SORTORDERINLISTNOPROGRAM = "sortOrderInListNoProgram"
    SORTORDERINVISITSCHEDULE = "sortOrderInVisitSchedule"
    STYLE = "style"
    TRANSLATIONS = "translations"
    UNIQUE = "unique"
    USER = "user"
    VALUETYPE = "valueType"

    def __str__(self) -> str:
        return str(self.value)
