from enum import Enum


class UserAddCollectionItemsJsonaddCollectionItemsXmlProperty(str, Enum):
    ACCESS = "access"
    ACCOUNTEXPIRY = "accountExpiry"
    ATTRIBUTEVALUES = "attributeValues"
    AVATAR = "avatar"
    BIRTHDAY = "birthday"
    CATDIMENSIONCONSTRAINTS = "catDimensionConstraints"
    CODE = "code"
    COGSDIMENSIONCONSTRAINTS = "cogsDimensionConstraints"
    CREATED = "created"
    CREATEDBY = "createdBy"
    DATAVIEWMAXORGANISATIONUNITLEVEL = "dataViewMaxOrganisationUnitLevel"
    DATAVIEWORGANISATIONUNITS = "dataViewOrganisationUnits"
    DISABLED = "disabled"
    DISPLAYNAME = "displayName"
    EDUCATION = "education"
    EMAIL = "email"
    EMPLOYER = "employer"
    EXTERNALAUTH = "externalAuth"
    FACEBOOKMESSENGER = "facebookMessenger"
    FAVORITE = "favorite"
    FAVORITES = "favorites"
    FIRSTNAME = "firstName"
    GENDER = "gender"
    HREF = "href"
    ID = "id"
    INTERESTS = "interests"
    INTRODUCTION = "introduction"
    INVITATION = "invitation"
    JOBTITLE = "jobTitle"
    LANGUAGES = "languages"
    LASTCHECKEDINTERPRETATIONS = "lastCheckedInterpretations"
    LASTLOGIN = "lastLogin"
    LASTUPDATED = "lastUpdated"
    LASTUPDATEDBY = "lastUpdatedBy"
    LDAPID = "ldapId"
    NATIONALITY = "nationality"
    OPENID = "openId"
    ORGANISATIONUNITS = "organisationUnits"
    PASSWORD = "password"
    PASSWORDLASTUPDATED = "passwordLastUpdated"
    PHONENUMBER = "phoneNumber"
    SELFREGISTERED = "selfRegistered"
    SETTINGS = "settings"
    SHARING = "sharing"
    SKYPE = "skype"
    SURNAME = "surname"
    TEISEARCHORGANISATIONUNITS = "teiSearchOrganisationUnits"
    TELEGRAM = "telegram"
    TRANSLATIONS = "translations"
    TWITTER = "twitter"
    TWOFACTORENABLED = "twoFactorEnabled"
    USER = "user"
    USERCREDENTIALS = "userCredentials"
    USERGROUPS = "userGroups"
    USERNAME = "username"
    USERROLES = "userRoles"
    WELCOMEMESSAGE = "welcomeMessage"
    WHATSAPP = "whatsApp"

    def __str__(self) -> str:
        return str(self.value)
